/* Generated by rayac C transpile backend v0.1 */
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#include "raya_rt.h"


void  raya_print(raya_Str s);
int64_t  main();

void  raya_print(raya_Str s) ;

int64_t  main() {
    int64_t a = 10;
    int64_t b = 3;
    return (a - b);
    raya_print((raya_Str){ .ptr = (uint8_t const*)"\"Hello from raya to c\"", .len = 22 });
}

