/* Generated by rayac C transpile backend v0.1 */
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#include "raya_rt.h"

typedef struct { uint8_t const* ptr; size_t len; } raya_Str;
typedef struct { void* ptr; size_t len; } raya_Slice;


int32_t  main();

int32_t  main() {
    return 42;
}

