/* Generated by rayac C transpile backend v0.1 */
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#include "raya_rt.h"


void  raya_print(raya_Str s);
int32_t  main();

void  raya_print(raya_Str s) ;

int32_t  main() {
    raya_print((raya_Str){ .ptr = (uint8_t const*)"\"Hello from Raya!\\n\"", .len = 20 });
    return 0;
}

