/* Generated by rayac C transpile backend v0.1 */
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#include "raya_rt.h"

struct raya_Point;

typedef struct raya_Point {
    int32_t x;
    int32_t y;
} raya_Point;

void  raya_print(raya_Str s);
int32_t  raya_Point_sum(struct raya_Point self);
int32_t  add(int32_t a, int32_t b);
int32_t  main();

void  raya_print(raya_Str s) ;

int32_t  raya_Point_sum(struct raya_Point self) {
    return (self.x + self.y);
}

int32_t  add(int32_t a, int32_t b) {
    return (a + b);
}

int32_t  main() {
    struct raya_Point p = (struct raya_Point){.x = 10, .y = 20};
    int32_t s = raya_Point_sum(p);
    int32_t t = add(s, 5);
    raya_print((raya_Str){ .ptr = (uint8_t const*)"\"Method test passed\\n\"", .len = 22 });
    return t;
}

